require("./DetailedStandard");
require("./Group");
require("./Teacher");
require("./LessonPlan");
require("./Standard");
require('./Student');
require('./Period');
require('./GroupType');
require('./Assessment');
